apiVersion: v1
kind: ConfigMap
metadata:
  name: alpaca-data-relay
data:
  bootstrap_servers: "pkc-ep9mm.us-east-2.aws.confluent.cloud:9092"
  group_id: "alpaca-data-relay"
  apca_api_base_url: "https://paper-api.alpaca.markets/v2"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-data-relay-deployment
spec:
  selector:
    matchLabels:
      app: alpaca-data-relay
  replicas: 1
  template:
    metadata:
      labels:
        app: alpaca-data-relay
    spec:
      containers:
      - name: alpaca-data-relay
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/alpaca-data-relay:${IMAGE_TAG}
        env:
        - name: SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_USERNAME
        - name: SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_PASSWORD
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: alpaca-data-relay
              key: bootstrap_servers
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: alpaca-data-relay
              key: group_id
        - name: APCA_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: alpaca-data-relay
              key: apca_api_base_url
        - name: APCA_API_KEY_ID
          valueFrom:
            secretKeyRef:
              name: alpaca
              key: APCA_API_KEY_ID
        - name: APCA_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: alpaca
              key: APCA_API_SECRET_KEY
